### ISSUE TITLE
Date formats in Timeline

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#13]
Hello 

We are currently using the Timeline and the side preview template for displaying metadata on top of the side document preview’s iframe. In both these things, the date format follows the US format. I noticed that the template on top of side preview document’s iframe is just displaying the modified date as it comes from the API (since we receive it as a string), so I guess there’s no changing it. But do you know if it’s possible to apply a different time format to the timeline?

![image](https://user-images.githubusercontent.com/65693851/99238717-6b1b4f00-283d-11eb-90c1-77d7ceb03ade.png)

For example, when I’m formatting the dates in my application, I always use the ToLocaleDateString() function, so that it will use the Locale date format. Is there a way to do the same with the Timeline?

**Comment by ericleib** [comment]
Hi Guillaume,
Actually, the timeline and the metadata components are supposed to be formatted in the language of the UI (which is not necessarily the language of the browser). This is done via the sqDate pipe, which listens to the change of the locale (via the intlService) and updates the display accordingly. So for example, when I switch to French, the modified date is displayed as follows:
![image](https://user-images.githubusercontent.com/12696790/99241212-d6453100-27fd-11eb-81e0-96b882bb117e.png)
Do you observe a different behavior ?

**Comment by Guillaume-Developer** [comment]
Eric,

I see... I would need to test this when I switch to Japanese in language in my application.
Unfortunately, I can't check right now, and I'm going on holiday for a week so I'll give you an update on next Tuesday. 
However, if you tell me it's using the UI language, then it's already answering my question I guess. So thank you!

**Comment by Guillaume-Developer** [comment]
The dates of the timeline and the metadata components are formatted in the language of the UI.
