### ISSUE TITLE
Japanese dakuten ( ﾞ ) and handakuten ( ﾟ ) in filters are deleted by the API at query time

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#18]
I noticed recently that the japanese characters using a dakuten ( ﾞ ) or a handakuten ( ﾟ ) in a filter are being transformed by the API at query time and the dakuten or handakuten are being deleted from the word. 
This leads to sounds like 「ザ」( [za] ) ou 「パ」( [pa] ) becoming 「サ」( [sa] ) et 「は」( [ha] ), which then makes the searches returns 0 results since the word changed... This doesn't happen in a normal text search, only when the dakuten or handakuten is on a word of the filter applied. Also, this doesn't appear to be an issue with the processing of the words when creating the expression, as I could see with the following log of the query object:

![query_pfizer](https://user-images.githubusercontent.com/65693851/104692963-2ed87200-574c-11eb-9cfc-01b2519934b9.PNG)

The above query object leads to the following query in the Sinequa engine:

`select ... from ... where text contains 'ファイザー' and (company contains 'ファイサー') and collection contains '*' and ...`

EDIT: this issue is extremely important since it causes almost half of the japanese words to be useless for filtering since they will always return 0 documents. Also, this doesn't happen in the profile search.

**Comment by ericleib** [comment]
Hi Guillaume,
I'll report the bug (note that for back-end bugs like this it'd be better to submit a support request via the support portal).

**Comment by Guillaume-Developer** [comment]
Hi Eric,

Alright, I'll know for next time! 
I'll write a support ticket for this, so that I can follow the issue on my side. Thanks!

**Comment by ericleib** [comment]
OK, you can mention that I already created a Bug ticket in your support ticket.
By the way, I assume that these symbols are diacritics? Are these words extracted as entities and displayed inside facets? If so, I'd be interested to see the raw data of the aggregations you get from the query web service.

**Comment by Guillaume-Developer** [comment]
I do believe these are diacritics yes.
Here's an example of the aggregation "company" gotten in the results object:

![image](https://user-images.githubusercontent.com/65693851/104702186-fab77e00-5758-11eb-97b7-61412e2239bb.png)

**Comment by ericleib** [comment]
This (server-side) bug has been solved in the hotfix Sinequa 11.4.1.2049, so I close this issue.
