### ISSUE TITLE
Demo projects in IE

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#2]
Hello,

I am currently learning to use the SBA functionality in Sinequa, and I seem to have walked upon an issue when running the vanilla-search app in IE.
I have carefully installed all the necessary dependencies to use angular in IE11, and I also made the appropriate modifications in the tsconfig.json file, but I get the error below when I serve the vanilla-search project in IE11. 

![image](https://user-images.githubusercontent.com/65693851/82516144-fea4e900-9b54-11ea-9bb1-406cd1565739.png)

![image](https://user-images.githubusercontent.com/65693851/82516161-0c5a6e80-9b55-11ea-9cbe-436b802dc8c0.png)

This error is specific to the vanilla-search project, it doesn't appear in the hello-search project or any other angular projects I created. 
I thought it might be a missing polyfill for a the implementation of a specific "for" loop in IE11, so I imported the full "core-js" package, but this didn't fix it.

### EDIT: After careful investigation and debugging, I could find that the modules below are the ones that are causing IE to bug.

- "@sinequa/components/baskets"
- "@sinequa/components/facet"
- "@sinequa/components/heatmap"
- "@sinequa/components/metadata"
- "@sinequa/components/preview"
- "@sinequa/components/result"
- "@sinequa/components/saved-queries"

**Comment by ericleib** [comment]
Thank you for reporting this. We have noticed similar problems with IE, but these bugs are a bit random and depend on the exact version you are using, so they are very hard to solve.
One thing for sure: `ng serve` does not support the differential loading feature that is needed for IE (See https://angular.io/guide/deployment#local-development-in-older-browsers). So you can either customize your `serve` target or just use `ng build` to test your app in IE.

**Comment by Guillaume-Developer** [comment]
Thank you for your answer, indeed it works fine with an `ng build`, so I will test the application like this in IE, as you recommended.
