### ISSUE TITLE
How can we customize export of documents to include non-column related data?

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#24]
Recently, we've been trying to add the search performed (text search + filters) to the export file obtained when downloading the documents' metadata. 
Unfortunately, we've come to realize that this endeavor was not possible due to the fact that the download file is prepared in the backend, and only the final file ready for download is sent back to the frontend. 
We thought that we could intercept the file before it being downloaded and change the filename through the header 'content-disposition' but it was unsuccessful. 

Do you have any idea how this could be implemented with the existing export query component or is this something that we would need to create a new component to implement?

**Comment by ericleib** [comment]
Hi Guillaume,
The front-end is probably the easy part. You could modify the existing component to your needs.
The difficulty is that there is currently no way to customize the backend for the export query... Perhaps you could implement your own export endpoint via plugin?

**Comment by Guillaume-Developer** [comment]
Hi Eric,
I understand, I'll talk to my team and see what we decide to do. I'll close this issue for now since your message is answering my question.
Thanks!
