### ISSUE TITLE
Extracts locations CSS not applied

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#25]
Hello,

I cannot explain why, but in some cases, the extracts locations CSS is not applied. In the screenshot below, for example, the matchlocations CSS is correctly applied, but not the extracts locations CSS.

![image](https://user-images.githubusercontent.com/65693851/112280539-750bfd80-8cc8-11eb-8223-24c55f16d0c5.png)
![image](https://user-images.githubusercontent.com/65693851/112280575-7fc69280-8cc8-11eb-8502-aa8814d277ed.png)

The CSS of the `extractslocations` class not being applied, the `fill` property is not set in the CSS, and it is automatically set as black. 
After some tests, I have noticed that in the stylesheet `preview.scss`, the code of `@mixin svgHighlight($term)` is not being applied for the `extractslocations` in this case. However, if I apply the CSS of `@mixin svgHighlight($term)` in `@mixin svgHighlightCurrent($term)`, this time it is correctly applied.
This phenomenon being applied to all the extracts present in the preview, it seems to lead to the fact that the `extractslocations` are considered as current highlight, event though they are not the current highlight?

Would you have an explanation or a solution for this? 
It doesn't seem appropriate to always apply the CSS in `@mixin svgHighlightCurrent($term)` since it is supposed to be for the current highlights only...

> @mixin svgHighlight($term) {
  $highlight: map-get($highlights, $term);
  $color: map-get($highlight, "color");
  $background-color: map-get($highlight, "background-color");
  $border: map-get($highlight, "border");
  @if $color != null {
    tspan.#{$term}:not(.sq-inactive) {
      fill: $color;
      font-weight: bold;
    }
  }
  @if $background-color == null {
    $background-color: rgba(0, 0, 0, 0);
  }
  rect.#{$term}:not(.sq-inactive) {
    fill: $background-color;
  }
  @if $border != null {
    line.#{$term} {
      border: $border;
    }
  }
}
@mixin svgHighlightCurrent($term) {
  $highlight: map-get($highlights, $term);
  $color: map-get($highlight, "color");
  $background-color: map-get($highlight, "background-color");
  $border: map-get($highlight, "border");
  @if $color != null {
    tspan.#{$term}:not(.sq-inactive) {
      fill: $color;
      font-weight: bold;
    }
  }
  @if $background-color == null {
    $background-color: rgba(0, 0, 0, 0);
  }
  rect.#{$term}:not(.sq-inactive).sq-current {
    fill: $background-color;
  }
  @if $border != null {
    line.#{$term} {
      border: $border;
    }
  }
}

**Comment by ericleib** [comment]
Hi Guillaume,
Does the problem occur only on SVG highlights / OCRed documents?
To be clear, the preview.css stylesheet (generated by preview.scss) is the same for every document, so the highlight CSS rules are always applied in the same way. So in your case, if the CSS rule is not enforced, it's more likely that there's something wrong with the HTML doc itself. When you inspect an element that should be highlighted, do you see the CSS rules from preview.css ? Perhaps they are being overriden by something ?

**Comment by Guillaume-Developer** [comment]
Hi Eric,

It looks like this happens with all the documents converted with the "_PptxToHtmlAndSvg" converter in Sinequa.
When I inspect the extract locations that should be highlighted, but are darkened, I do not see any CSS rules. I do not see the rules that should be present with my CSS, nor any other rules that might be overriding it.

**Comment by ericleib** [comment]
I had a look at the code, and in fact it is normal that there is no sq-current for SVG elements, because we use a different technique:
```
    private setHighlightSelection(elt: Element, isFirst: boolean, isLast: boolean): void {
        if (this.isSvgElement(elt)) {
            this.setHighlightSelectionSVG(elt, isFirst, isLast);
        }
        else {
            this.setHighlightSelectionHTML(elt, isFirst, isLast);
        }
    }
```
For SVG elements, we insert lines (with class "sq-svg") around the relevant extract or entity. Our default preview.scss stylesheet includes some styles for these lines:

```
line.sq-svg {
    stroke: rgb(5, 5, 5);
    stroke-width: 2;
    stroke-dasharray: 2, 2;
}
```
Do you see these lines added to the DOM when you navigate from extract to extract ? (Note: I think it was done like this because with SVG you have limited control over the rect's borders. Drawing lines provides more flexibility for styling)

**Comment by Guillaume-Developer** [comment]
I do see these lines, and I also think it is a good idea, but this behavior makes it impossible to only activate the highlight on the currently selected extract. Do you think it is possible to also add a class to the rect of the currently selected extracts?

**Comment by ericleib** [comment]
Yes absolutely, could be called sq-current-svg? Do you want to make a PR for this ?

**Comment by Guillaume-Developer** [comment]
Yes sure, I'll make a PR this week probably, I'll let you know! The code to add should be fairly similar to the code of the function `setHighlightSelectionHTML` am I right?

**Comment by ericleib** [comment]
Yes, it should be the same. Also don't forget the code to remove this class when changing selection and/or removing highlights.

**Comment by Guillaume-Developer** [comment]
I realized I posted this issue while working with the old version of the SBA, so I decided to upgrade my version with the new version available here. 
After the upgrade, I have another problem showing up, which is the fact that the `rect` are not even positioned correctly anymore. The dotted box around the extract doesn't appear anymore, because the position is not set. The original `rect` element also doesn't have any position set.

I did not perform any changes on my own, I just applied the new version of the code v15.0.0. Before that we were still using the version 1.11.1.
Again, this issue appears only for SVG highlights / OCRed documents?

OLD VERSION (v1.11.1):
![image](https://user-images.githubusercontent.com/65693851/113257594-cb4ef100-9305-11eb-862f-2631da88e032.png)

NEW VERSION (v15.0.0):
![image](https://user-images.githubusercontent.com/65693851/113257651-e02b8480-9305-11eb-9b43-f3673ae42b6d.png)

**Comment by ericleib** [comment]
Is this the result of upgrading ONLY the SBA, or did you update as well the Sinequa server?

**Comment by ericleib** [comment]
Could you check in the debugger if `previewDocument.setSvgBackgroundPositionAndSize();` is called after the HTML preview is loaded?

**Comment by Guillaume-Developer** [comment]
I only update the SBA. For the Sinequa server, I am using the version 11.5.0.2008 in both cases.
The function `previewDocument.setSvgBackgroundPositionAndSize();` is called, and the `tspan` are all fetched correctly.

![image](https://user-images.githubusercontent.com/65693851/113266858-b166db80-9310-11eb-82f9-ac7221ad0565.png)

**Comment by Guillaume-Developer** [comment]
I logged a bit deeper:

```
private resizeSvgBackground(rect: Element, tspan: SVGTSpanElement): void {
        let elt: Element = tspan;
        while (elt.tagName !== "text") {
            elt = elt.parentNode as Element;
            if (elt == null) break;
        }
        const text: SVGTextElement = elt as SVGTextElement;
        console.log(text);
        const textBoxPixel: ClientRect = text.getBoundingClientRect();
        console.log(textBoxPixel);
        const textBoxSVG: SVGRect = text.getBBox();
        console.log(textBoxSVG);
        if (textBoxPixel.height === 0 || textBoxPixel.width === 0) return;
        const scaleX = textBoxSVG.width / textBoxPixel.width;
        const scaleY = textBoxSVG.height / textBoxPixel.height;
        const deltaX = 2 * scaleX;
        const deltaY = 2 * scaleY;

        const firstCharRect = tspan.getExtentOfChar(0);
        const tspanWidth = tspan.getComputedTextLength();

        rect.setAttribute("x", String(firstCharRect.x - deltaX));
        rect.setAttribute("y", String(firstCharRect.y - deltaY));
        rect.setAttribute("width", String(tspanWidth + 2 * deltaX));
        rect.setAttribute("height", String(textBoxSVG.height + 2 * deltaY));
        const valueTransform = text.getAttribute("transform");
        if (valueTransform) rect.setAttribute("transform", valueTransform);
    }
```

The line `console.log(textBoxPixel);` only logs an object:

```
DOMRect {x: 0, y: 0, width: 0, height: 0, top: 0, …}
  bottom: 0
  height: 0
  left: 0
  right: 0
  top: 0
  width: 0
  x: 0
  y: 0
  __proto__: DOMRect
```

It feels like the loading of the SVG background happens before the html has fully calculated the position of the elements maybe?

**Comment by ericleib** [comment]
Yes, something might have changed in that respect. I will create a ticket and keep you posted, will update the release/11.5.0 branch when we have a fix. Thanks for investigating!

**Comment by Guillaume-Developer** [comment]
Alright, I'll wait for the fix. Thanks a lot!

**Comment by ericleib** [comment]
The latest version pushed to this repo should fix this issue. Can you give it a try and confirm that it works?

**Comment by ericleib** [comment]
Did you have a chance to give it a try?

**Comment by Guillaume-Developer** [comment]
Sorry for the late answer, I tried the fix and the highlight is back indeed. Thanks a lot.
