### ISSUE TITLE
Autosuggest dropdown does not close when using search button

### ISSUE THREAD

**Issue by Pascal-Tribollet** [sinequa/sba-angular#30]
If autosuggest dropdown appear, enter in search input correctly start search and close it but clicking on search button only start search

**Comment by ericleib** [comment]
We pushed an update that should resolve this issue. Can you pull the latest version and confirm that it works?

**Comment by ericleib** [comment]
Any update ?

**Comment by Pascal-Tribollet** [comment]
Same fix successfully applied in our applications.
