### ISSUE TITLE
Audit personalized events

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#31]
Hello,

Is it possible to add personalized audit events outside the available events in `AuditEventType`? 
For example, I'd like to register a new audit event for the views clicked by the user, to have an insight of which views are the most used. However, with the current state of the audit web service, there is no way of doing such thing.

Thank you.

**Comment by ericleib** [comment]
Hello,

Yes, it is possible to register custom events. Did you have a look at this page of the docs?
https://sinequa.github.io/sba-angular/tipstricks/audit.html

**Comment by Guillaume-Developer** [comment]
Indeed, it is what I was looking for! Sorry for the inconvenience, didn't think of looking there...
