### ISSUE TITLE
Result selector broken since 11.6.1

### ISSUE THREAD

**Issue by JonathanBrose** [sinequa/sba-angular#38]
Since the Update to 11.6.1 The sq-result-selector is broken.
It doesn't react to the user selecting documents and doesn't display the selected count any more. Also there are no Actions like the labels or baskets showing up, because it doesn't seem to register the selection changes. When I select all at once it shows the count but still no actions...

**Comment by ericleib** [comment]
Hello,
This bug should be fixed in the latest version that we pushed early last week. The bug was introduced when we released the 11.6.1, but we pushed the fix to this repository (as well as on NPM and in the SBA workspace packaged in the Sinequa release).

**Comment by JonathanBrose** [comment]
Alright, 
I pulled the latest version from master and merged it into our project. It works again. 
Thanks.
