### ISSUE TITLE
Preview extracts not displaying in IE11

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#4]
Hello,

I recently found a bug with IE11 when trying to display the extracts of the document preview page.
The console only says that the 'forEach' function doesn't exist for the type.
After some research on the error, I found that the type mentioned in the error is probably the 'NodeList' type so I tried to add the corresponding polyfill to fix the issue (in the project file "polyfills.ts"), but without success.
I also tried to modify the code of the components object that is used at the loading of the extracts:

`for (let i = 0; i < nodes.length; i++) {
     let n = nodes[i];
     text += (n['innerHTML'] || n.textContent);
}
//nodes.forEach(n => text += (n['innerHTML'] || n.textContent));`

This also didn't prove useful.
I am currently running out of ideas, and time, to fix this issue so I am opening a ticket here in case someone could find a fix or an explanation to this.
Note that every tests I did were done in production mode `ng build project --prod`, and I did build one more time the components after the modification I performed.

Thank you.

**Comment by ericleib** [comment]
Hi Guillaume,
These IE11 issues are unfortunately hard to detect and prevent... We just updated the codebase on the repository, can you `git pull`, recompile everything and try again?
If this doesn't work, can you tell us more about the problem? What do you see exactly (the app won't run at all, or it crashes when you perform a specific action / open a specific component)? Are you starting from an existing app and seeing the problem when you do one change? (if so can you isolate the specific problem, ideally down to the line of code that cause the problem)
Common things to check for IE:
- The versions of IE you target should be listed in the `browserslist` file of your app.
- By default, only the production build will work for IE, so `ng serve` won't work. The `dist` folder must contain `es5` JavaScript files (in addition to `es2015`).
- In `angular.json` you should have `buildOptimizer: fase` for your project (we have noticed it can cause some elusive bugs if true)
- You polyfills file should contain this line: `import 'core-js/modules/es.array.includes';` (the path has changed when we migrated to angular 9)

**Comment by Guillaume-Developer** [comment]
Hi Eric,
The new version has apparently fixed the bug I had. Everything is now fine.
Thanks a lot for your time.
