### ISSUE TITLE
Error when using a second label webservice

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#53]
I tried recently to use more than one label webservice in my code but realized that the webservice placed in second position was always returning an error when used.
Moving the same webservice in first position will make the error disappear though. Find below a piece of code that I use to call the specific webservice I added.

``
let default_cclabels = this.appService.cclabels;

    this.appService.cclabels = this.appService.getWebService("key_assets_labels");

    if (this.keyAssetFlag) {
      this.labelsWebService
        .add([this.keyAssetsConfig.tag], [this.record.id], true)
        .pipe(takeUntil(this.ngUnsubscribe))
        .subscribe((res) => {
          this.appService.cclabels = default_cclabels;
        });
    } else {
      this.labelsWebService
        .remove([this.keyAssetsConfig.tag], [this.record.id], true)
        .pipe(takeUntil(this.ngUnsubscribe))
        .subscribe((res) => {
          this.appService.cclabels = default_cclabels;
        });
    }
``

The error that I am getting when using this label webservice is the following one: 

![image](https://user-images.githubusercontent.com/65693851/148470920-69952db6-4e6e-4862-9dd9-3bba60ccd773.png)

> {methodresult: "error", errorCode: 4, errorCodeText: "invalid request",…}
> errorCode: 4
> errorCodeText: "invalid request"
> errorMessage: "User cannot remove public labels"
> methodresult: "error"

WEBAPP LOGS

> 2022-01-07 09:40:32 api url 'v1/labels'
> 2022-01-07 09:40:32 :ND:Session.DoLogin:sinequa|admin
> 2022-01-07 09:40:32 >>:ss:ResolveProfile
> 2022-01-07 09:40:32 user settings read for sinequa|admin
> 2022-01-07 09:40:32 >>:ss:GetUserRights
> 2022-01-07 09:40:32 >>:cc:CalculateSessionRights:sinequa|admin +F
> 2022-01-07 09:40:32 >>:nd:CalculateUserRightsV3(1,4192)
> 2022-01-07 09:40:32 <<:nd:CalculateUserRightsV3 : 0.12
> 2022-01-07 09:40:32 <<:cc:CalculateSessionRights:sinequa|admin +F : 63.959 ms
> 2022-01-07 09:40:32 <<:ss:GetUserRights : 64.027 ms
> 2022-01-07 09:40:32 <<:ss:ResolveProfile : 64.257 ms
> 2022-01-07 09:40:32 SessionUiLanguage=English
> 2022-01-07 09:40:32 SessionUiDateFormat=
> 2022-01-07 09:40:32 Sys.LangCode=English
> 2022-01-07 09:40:32 DoOverrideUser: no user specified in override user parameter
> 2022-01-07 09:40:32 error : labels error n° 4 (invalid request) : User cannot remove public labels
> 2022-01-07 09:40:32 http set status : 500
> 2022-01-07 09:40:32 xrest labels : 63 ms

**Comment by ericleib** [comment]
Hi Guillaume,
Unfortunately, this is a limitation of the platform... Even though you can configure multiple label web services, only the first one is taken into account.
I suggest you raise a support ticket so this issue has more visibility by r&d.

**Comment by Guillaume-Developer** [comment]
Hi Eric,

I just noticed this myself while playing with the REST API directly... 
I already had a support ticket up (where they told me to ask the developers directly at first), so I updated now with a question about the possibility to expand the labels REST API to be able to use more than one label web service.

Thanks!
