### ISSUE TITLE
Search on spelling correction does not update the query analysis

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#54]
Hi, 

I noticed while working with the spelling correction (sq-did-you-mean) component that when clicking on a proposed correction, the query correctly updates, but the content of the query analysis is not updated.
Not sure if this is an issue on the SBA side or backend side though...

**Comment by ericleib** [comment]
Hi Guillaume,
Not sure whether this is expected behavior or not, but for sure it's a backend issue.

**Comment by Guillaume-Developer** [comment]
Alright, I opened a ticket on the support site. Should we keep close this ticket or wait for the answer from the support?

**Comment by ericleib** [comment]
I guess we can close it.
