### ISSUE TITLE
Build error for @sinequa/components/results-view

### ISSUE THREAD

**Issue by shravanv90** [sinequa/sba-angular#6]
Getting a build build error while building sinequa components. Trying to build it via devops

ERROR: projects/components/results-view/results-scatter-view/results-scatter-view.ts:234:9 - error TS2769: No overload matches this call.
 Overload 1 of 4, '(name: string, value: null): Selection<SVGCircleElement, ValueItem, SVGGElement, ValueItem[]>', gave the following error.

the other components are getting built, but when it reaches result-view it gives an error.

Could you please help with this?

**Comment by ericleib** [comment]
Hello,
Can you tell us more about the conditions that led to this error? Is this from a clean download of this repository? Which commands did you run?
These types of error can come from outdated libraries in node_modules, which can happen if you updated the repository with a `git pull`, but forgot to run `npm install`.

**Comment by shravanv90** [comment]
Thanks for the response.

i am trying to build it from Azure devops, and all the steps are run in sequence.

npm install
npm run buildcore
npm run build components

**Comment by ericleib** [comment]
Which version of node/npm are you using? Shouldn't make a difference, but we never know.
Also, what version of the SBA repository are you using? The current one ? (1.1.0 in package.json)

**Comment by ericleib** [comment]
Any update about this issue, or can I close it?

**Comment by shravanv90** [comment]
The issue got resolved, used the latest package.json

**Comment by shravanv90** [comment]
Thanks eric
