### ISSUE TITLE
Issue with recent queries date revival for dates different from GMT+0

### ISSUE THREAD

**Issue by Guillaume-Developer** [sinequa/sba-angular#87]
I've noticed recently while playing with the recent queries that the date revival code in the RecentQueriesService is actually making the dates of revived queries go backward. 
For example, with GMT+9, the date built with `const date = Utils.toDate(rq.date);` will have the correct time and the correct timezone applied, but then when assigning it `rq.date = date;`, the `rq.date` will be in GMT+0, which means that the time will go 9 hours back and be saved as is. 

### EDIT
Nervermind, I realized that the code was fixed in the newest version, can you confirm? 
Anyway, we are not using it at the moment so I'll just apply a workaround in the meantime.

**Comment by ericleib** [comment]
Yes, I can confirm this was fixed in version 11.8.0!
